export const paymentDataRows = [
  {
    id: 1,
    date: "16-07-2022",
    payment_method: "Credit Card",
    amount: "200 unit",
    status: "Paid",
    action: "Adjust",
  },
  {
    id: 2,
    date: "16-07-2022",
    payment_method: "Credit Card",
    amount: "200 unit",
    status: "Stock out",
    action: "Adjust",
  },
  {
    id: 3,
    date: "16-07-2022",
    payment_method: "Credit Card",
    amount: "200 unit",
    status: "Pending",
    action: "Adjust",
  },
  {
    id: 4,
    date: "16-07-2022",
    payment_method: "Credit Card",
    amount: "200 unit",
    status: "Stock out",
    action: "Adjust",
  },
  {
    id: 5,
    date: "16-07-2022",
    payment_method: "Credit Card",
    amount: "200 unit",
    status: "Paid",
    action: "Adjust",
  },
  {
    id: 6,
    date: "16-07-2022",
    payment_method: "Credit Card",
    amount: "200 unit",
    status: "Failed",
    action: "Adjust",
  },
  {
    id: 7,
    date: "16-07-2022",
    payment_method: "Credit Card",
    amount: "200 unit",
    status: "Pending",
    action: "Adjust",
  },
  {
    id: 8,
    date: "16-07-2022",
    payment_method: "Credit Card",
    amount: "200 unit",
    status: "Failed",
    action: "Adjust",
  },
  {
    id: 9,
    date: "16-07-2022",
    payment_method: "Credit Card",
    amount: "200 unit",
    status: "Stock out",
    action: "Adjust",
  },
];
