import imgOne from "../../assets/5.png";
import imgTwo from "../../assets/3.png";

export const rows = [
  {
    id: 1,
    orderId: "#001701",
    img: imgOne,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "29-07-22",
    customer: "Pattrick Leach",
    cost: 6.49,
    shipping: "$8.49",
    fulfillment: "Shipped",
    order_status: "Delivered",
  },
  {
    id: 2,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "25-07-22",
    customer: "Pattrick Leach",
    cost: 0.49,
    shipping: "$8.49",
    fulfillment: "Fulfilled",
    order_status: "Unshipped",
  },
  {
    id: 3,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "10-07-22",
    customer: "Pattrick Leach",
    cost: 1.49,
    shipping: "$8.49",
    fulfillment: "In Process",
    order_status: "In Transit",
  },
  {
    id: 4,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "16-07-22",
    customer: "Pattrick Leach",
    cost: 2.49,
    shipping: "$8.49",
    fulfillment: "Shipped",
    order_status: "Delivered",
  },
  {
    id: 5,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "13-07-22",
    customer: "Pattrick Leach",
    cost: 4.49,
    shipping: "$8.49",
    fulfillment: "Fulfilled",
    order_status: "Unshipped",
  },
  {
    id: 6,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "09-07-22",
    customer: "Pattrick Leach",
    cost: 9.49,
    shipping: "$8.49",
    fulfillment: "In Process",
    order_status: "In Transit",
  },
  {
    id: 7,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "19-07-22",
    customer: "Pattrick Leach",
    cost: 8.49,
    shipping: "$8.49",
    fulfillment: "Shipped",
    order_status: "Delivered",
  },
  {
    id: 8,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: 5.49,
    shipping: "$8.49",
    fulfillment: "Shipped",
    order_status: "Delivered",
  },
  {
    id: 9,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "20-07-22",
    customer: "Pattrick Leach",
    cost: 6.49,
    shipping: "$8.49",
    fulfillment: "Shipped",
    order_status: "Delivered",
  },
];

export const disputeRows = [
  {
    id: 1,
    orderId: "#001701",
    img: imgOne,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: "$6.49",
    shipping: "$8.49",
    dispute: "POD",
    dispute_status: "Completed",
  },
  {
    id: 2,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: "$6.49",
    shipping: "$8.49",
    dispute: "POD",
    dispute_status: "Pending",
  },
  {
    id: 3,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: "$6.49",
    shipping: "$8.49",
    dispute: "Local Tracking",
    dispute_status: "Completed",
  },
  {
    id: 4,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: "$6.49",
    shipping: "$8.49",
    dispute: "Resend",
    dispute_status: "Completed",
  },
  {
    id: 5,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: "$6.49",
    shipping: "$8.49",
    dispute: "Resend",
    dispute_status: "Pending",
  },
  {
    id: 6,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: "$6.49",
    shipping: "$8.49",
    dispute: "Refund",
    dispute_status: "Pending",
  },
  {
    id: 7,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: "$6.49",
    shipping: "$8.49",
    dispute: "POS",
    dispute_status: "Completed",
  },
  {
    id: 8,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: "$6.49",
    shipping: "$8.49",
    dispute: "Resend",
    dispute_status: "Pending",
  },
  {
    id: 9,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    date: "30-07-22",
    customer: "Pattrick Leach",
    cost: "$6.49",
    shipping: "$8.49",
    dispute: "Resend",
    dispute_status: "Pending",
  },
];

export const orderTrackingRows = [
  {
    id: 1,
    orderId: "#001701",
    img: imgOne,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    trackingId: "YT22225445445446456",
    destination: "Netherlands",
    time_in_transit: "11 Days",
    shipping: "$8.49",
    dispute: "Shipped",
    order_status: "Completed",
  },
  {
    id: 2,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    trackingId: "YT22225445445446456",
    destination: "Netherlands",
    time_in_transit: "11 Days",
    shipping: "$8.49",
    dispute: "Shipped",
    order_status: "In Transit",
  },
  {
    id: 3,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    trackingId: "YT22225445445446456",
    destination: "Netherlands",
    time_in_transit: "12 Days",
    shipping: "$8.49",
    dispute: "Unshipped",
    order_status: "Completed",
  },
  {
    id: 4,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    trackingId: "YT22225445445446456",
    destination: "Netherlands",
    time_in_transit: "11 Days",
    shipping: "$8.49",
    dispute: "Unshipped",
    order_status: "In Transit",
  },
  {
    id: 5,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    trackingId: "YT22225445445446456",
    destination: "Netherlands",
    time_in_transit: "09 Days",
    shipping: "$8.49",
    dispute: "Resend",
    order_status: "Unshipped",
  },
  {
    id: 6,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    trackingId: "YT22225445445446456",
    destination: "Netherlands",
    time_in_transit: "19 Days",
    shipping: "$8.49",
    dispute: "Shipped",
    order_status: "Unshipped",
  },
  {
    id: 7,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    trackingId: "YT22225445445446456",
    destination: "Netherlands",
    time_in_transit: "10 Days",
    shipping: "$8.49",
    dispute: "Unshipped",
    order_status: "Completed",
  },
  {
    id: 8,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    trackingId: "YT22225445445446456",
    destination: "Netherlands",
    time_in_transit: "11 Days",
    shipping: "$8.49",
    dispute: "Unshipped",
    order_status: "Unshipped",
  },
  {
    id: 9,
    orderId: "#001701",
    img: imgTwo,
    title: "Foundation Flip Flop",
    category: "Footwear",
    variant: "Sports",
    color: "gray",
    invoiceId: "INVSD750073X",
    productId: "S90M032",
    trackingId: "YT22225445445446456",
    destination: "Netherlands",
    time_in_transit: "11 Days",
    shipping: "$8.49",
    dispute: "Shipped",
    order_status: "Unshipped",
  },
];
