import productImg from "../../../assets/1.png";
import productImg2 from "../../../assets/2.png";
import productImg3 from "../../../assets/3.png";

export const rows = [
  {
    id: 1,
    product: {
      img: productImg,
      title: "Foundation Flip Flop",
    },
    sku: "14:200048",
    color: "Blue",
    size: "M",
    cost: "$4.56",
    shipping_cost: "$2.32",
    price_value: "4.04",
    compare_price_value: "4.56",
  },
  {
    id: 2,
    product: {
      img: productImg2,
      title: "Foundation Flip Flop",
    },
    sku: "14:200048",
    color: "Green",
    size: "L",
    cost: "$4.56",
    shipping_cost: "$2.32",
    price_value: "4.04",
    compare_price_value: "4.56",
  },
  {
    id: 3,
    product: {
      img: productImg3,
      title: "Foundation Flip Flop",
    },
    sku: "14:200048",
    color: "Red",
    size: "XL",
    cost: "$4.56",
    shipping_cost: "$2.32",
    price_value: "4.04",
    compare_price_value: "4.56",
  },
  {
    id: 4,
    product: {
      img: productImg3,
      title: "Foundation Flip Flop",
    },
    sku: "14:200048",
    color: "Blue",
    size: "XXL",
    cost: "$4.56",
    shipping_cost: "$2.32",
    price_value: "4.04",
    compare_price_value: "4.56",
  },
  {
    id: 5,
    product: {
      img: productImg3,
      title: "Foundation Flip Flop",
    },
    sku: "14:200048",
    color: "Green",
    size: "M",
    cost: "$4.56",
    shipping_cost: "$2.32",
    price_value: "4.04",
    compare_price_value: "4.56",
  },
  {
    id: 6,
    product: {
      img: productImg2,
      title: "Foundation Flip Flop",
    },
    sku: "14:200048",
    color: "Red",
    size: "L",
    cost: "$4.56",
    shipping_cost: "$2.32",
    price_value: "4.04",
    compare_price_value: "4.56",
  },
  {
    id: 7,
    product: {
      img: productImg2,
      title: "Foundation Flip Flop",
    },
    sku: "14:200048",
    color: "Blue",
    size: "XL",
    cost: "$4.56",
    shipping_cost: "$2.32",
    price_value: "4.04",
    compare_price_value: "4.56",
  },
  {
    id: 8,
    product: {
      img: productImg2,
      title: "Foundation Flip Flop",
    },
    sku: "14:200048",
    color: "Red",
    size: "XXL",
    cost: "$4.56",
    shipping_cost: "$2.32",
    price_value: "4.04",
    compare_price_value: "4.56",
  },
  {
    id: 9,
    product: {
      img: productImg2,
      title: "Foundation Flip Flop",
    },
    sku: "14:200048",
    color: "Green",
    size: "M",
    cost: "$4.56",
    shipping_cost: "$2.32",
    price_value: "4.04",
    compare_price_value: "4.56",
  },
];
